import java.awt.Button;
import java.awt.Color;
import java.awt.Container;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JSlider;
import javax.swing.Timer;


public class gui extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form gui
     */
    public gui() {
    	System.out.println("G object created");
    	//initComponents1();
        initComponents2();
       // display();
    }
    
    

    String val1="1";
    String val2="2";
    String val3="3";
    String val4="4";
    private String tempstore[]=new String[4];{

        tempstore[0]=val1;
        tempstore[1]=val2;
        tempstore[2]=val3;
        tempstore[3]=val4;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents1() 
    {
    	
    	jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();      
        help_button = new javax.swing.JButton();
        button1.addActionListener(this);
        button2.addActionListener(this);
        button3.addActionListener(this);
        button4.addActionListener(this);
		
        
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(15,100,40));
        

       String string = "/card.jpg";
    
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(string))); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(string))); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(string))); // NOI18N
        jButton4.setText("jButton4");
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
     
        generate();
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(153, 153, 153)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

      
        
        array[0] = jButton1;
        array[1] = jButton2;
        array[2] = jButton3;
        
         pack();
     }// </editor-fold>
    private void initComponents2() {
    	j2Panel1 = new javax.swing.JPanel();
        j2Label1 = new javax.swing.JLabel();
        j2Label2 = new javax.swing.JLabel();
        j2Label3 = new javax.swing.JLabel();
        j2Button3 = new javax.swing.JButton();
        j2Button1 = new javax.swing.JButton();
        j2Button4 = new javax.swing.JButton();
        j2Button4.addActionListener(this);
        j2Button1.addActionListener(this);
        j2Button3.addActionListener(this);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j2Panel1.setBackground(new java.awt.Color(0, 0, 0));

        j2Label1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        j2Label1.setForeground(new java.awt.Color(204, 0, 0));
        j2Label1.setText("     SET 4 ");
        String s1="/card1.jpg";
        String s2="/card23.jpg";
        j2Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource(s1))); // NOI18N
        j2Label2.setText("j2Label2");

        j2Label3.setIcon(new javax.swing.ImageIcon(getClass().getResource(s2))); // NOI18N
        j2Label3.setText("j2Label3");

        j2Button3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        j2Button3.setForeground(new java.awt.Color(255, 51, 51));
        j2Button3.setText("EXIT");

        j2Button1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        j2Button1.setForeground(new java.awt.Color(255, 51, 51));
        j2Button1.setText("INSTRUCTIONS");

        j2Button4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        j2Button4.setForeground(new java.awt.Color(255, 51, 51));
        j2Button4.setText("PLAY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(j2Panel1);
        j2Panel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(j2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(j2Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(j2Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(j2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(j2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129)
                .addComponent(j2Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(j2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(j2Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j2Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(j2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
     }// </editor-fold>
    
    
    private void initComponents3()
    {
    	  j3Panel1 = new javax.swing.JPanel();
          j3ScrollPane2 = new javax.swing.JScrollPane();
          j3TextArea2 = new javax.swing.JTextArea();
          j3ScrollPane1 = new javax.swing.JScrollPane();
          j3TextArea1 = new javax.swing.JTextArea();
          j3Button1 = new javax.swing.JButton();
          j3Button1.addActionListener(this);
          setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
          setBackground(new java.awt.Color(255, 0, 0));

          j3Panel1.setOpaque(false);

          j3ScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
          j3ScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

          j3TextArea2.setBackground(new java.awt.Color(204, 204, 204));
         
          j3TextArea2.setColumns(20);
          j3TextArea2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
          j3TextArea2.setRows(5);
          j3TextArea2.setText("  INSTRUCTIONS");
          j3ScrollPane2.setViewportView(j3TextArea2);

          j3ScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

          j3TextArea1.setBackground(new java.awt.Color(204, 204, 204));
          j3TextArea1.setColumns(20);
          j3TextArea1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
          j3TextArea1.setRows(5);
          
          //Node temp;
          //temp = sl.head;
          //j3TextArea1.setText(temp.key);
          while(temp != null)
          {
        	  String s = j3TextArea1.getText();
        	  j3TextArea1.setText(s + temp.key + "\n");
        	  temp = temp.link;
          }
          j3ScrollPane1.setViewportView(j3TextArea1);

          j3Button1.setText("CLOSE");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(j3Panel1);
          j3Panel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                  .addContainerGap(245, Short.MAX_VALUE)
                  .addComponent(j3ScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(179, 179, 179)
                  .addComponent(j3Button1)
                  .addGap(27, 27, 27))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(j3ScrollPane1)
                  .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(j3ScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(j3Button1))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(j3ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(53, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addComponent(j3Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(j3Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
    }
    
    private void initComponents4() {

        j4Panel1 = new javax.swing.JPanel();
        j4Panel2 = new javax.swing.JPanel();
        j4Button1 = new javax.swing.JButton();
        j4Button3 = new javax.swing.JButton();
        j4Button4 = new javax.swing.JButton();
        j4Button6 = new javax.swing.JButton();
        j4Button7 = new javax.swing.JButton();
        j4Button8 = new javax.swing.JButton();
        j4Button9 = new javax.swing.JButton();
        j4Button5 = new javax.swing.JButton();
        j4Button10 = new javax.swing.JButton();
        j4Button11 = new javax.swing.JButton();
        j4Button12 = new javax.swing.JButton();
        j4Button13 = new javax.swing.JButton();
        j4Button14 = new javax.swing.JButton();
        j4Button15 = new javax.swing.JButton();
        j4Button16 = new javax.swing.JButton();
        j4TextField1 = new javax.swing.JTextField();
        j4Button17 = new javax.swing.JButton();
        j4Button18 = new javax.swing.JButton();
        j4Button19 = new javax.swing.JButton();
        j4Button18.addActionListener(this);
        j4Button17.addActionListener(this);
        
        
       // javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       /* jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );*/

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j4Panel2.setBackground(new java.awt.Color(15, 100, 40));
        j4Panel2.setBackground(new java.awt.Color(15, 100, 40));
        
        
        //j4Button1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button1.setText(Integer.toString(c.l2.head.info));
        
        //j4Button19.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button19.setText(Integer.toString(c.l2.head.right.info));
        
        //j4Button3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button3.setText(Integer.toString(c.l2.head.right.right.info));

        //j4Button4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button4.setText(Integer.toString(c.l2.head.right.right.right.info));

        if(player1==false)
        {
        //j4Button6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button6.setText(Integer.toString(c.l3.head.info));
        }

        //j4Button7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button7.setText(Integer.toString(c.l3.head.right.info));

        //j4Button8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button8.setText(Integer.toString(c.l3.head.right.right.info));

        //j4Button9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button9.setText(Integer.toString(c.l3.head.right.right.right.info));
        
        if(player1 != true && player2!=true )//&& c.l4.check())
        {
        //j4Button5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button5.setText(Integer.toString(c.l4.head.info));
        }

        //j4Button10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button10.setText(Integer.toString(c.l4.head.right.info));

        //j4Button11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button11.setText(Integer.toString(c.l4.head.right.right.info));

        //j4Button12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 3));
        j4Button12.setText(Integer.toString(c.l4.head.right.right.right.info));

        if(player1 != true && player2!=true && player3!=true)// && c.l1.check())
        j4Button13.setText(Integer.toString(c.l1.head.info));

        j4Button14.setText(Integer.toString(c.l1.head.right.info));

        j4Button15.setText(Integer.toString(c.l1.head.right.right.info));

        j4Button16.setText(Integer.toString(c.l1.head.right.right.right.info));
        
        if(user==false)
        {
        
        	j4TextField1.setText("      "+winner +" Wins!!");//"+ " player 1 ="+ score2 + "player 2=" +score3+ " player 3= "+score4+ " user ="+score1);
        	
           // j4TextField1).setIco(new javax.swing.ImageIcon(getClass().getResource(string)));
        }
        else
        {
        	j4TextField1.setText("    YOU WIN!!!");
        }
        	j4TextField1.setBackground(Color.DARK_GRAY);
        	j4TextField1.setBackground(color.darker());
        	j4TextField1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16));
      //  j4TextField1.setBorder(
        j4Button17.setText("SCORE");

        j4Button18.setText("PLAY AGAIN");



        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(j4Panel2);
        j4Panel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(j4Button14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j4Button13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(j4Button16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j4Button15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(j4Button18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4Button19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j4Button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j4Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j4TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(j4Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j4Button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(j4Button11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j4Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(j4Button7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j4Button8)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(j4Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j4Button6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j4Button17)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4Button7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(j4Button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j4Button9, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(j4Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j4TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4Button17)
                            .addComponent(j4Button18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j4Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4Button19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j4Button3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(j4Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j4Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j4Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4Button14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4Button13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4Button16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4Button15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j4Panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j4Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    void initComponents5()
    {
    	j5Panel1 = new javax.swing.JPanel();
        j5textField1 = new java.awt.TextField();
        j5textField2 = new java.awt.TextField();
        j5textField3 = new java.awt.TextField();
        j5textField4 = new java.awt.TextField();
        j5button1 = new java.awt.Button();
        j5button2 = new java.awt.Button();
       j5button1.addActionListener(this);
       j5button2.addActionListener(this);
       while(s1.tos!=-1)
		{
			score1=score1+s1.pop();
		}
		while(s2.tos!=-1)
		{
			score2=score2+s2.pop();
		}
		while(s3.tos!=-1)
		{
			score3=score3+s3.pop();
		}
		while(s4.tos!=-1)
		{
			score4=score4+s4.pop();
		}
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j5Panel1.setBackground(new java.awt.Color(0,0,0));

        j5textField1.setBackground(new java.awt.Color(255,255,255));
        j5textField1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        j5textField1.setText("textField1");

        j5textField2.setBackground(new java.awt.Color(255,255,255));
        j5textField2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        j5textField2.setText("textField1");

        j5textField3.setBackground(new java.awt.Color(255,255,255));
        j5textField3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        j5textField3.setText("textField1");

        j5textField4.setBackground(new java.awt.Color(255,255,255));
        j5textField4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        j5textField4.setText("textField1");
        j5button1.getAccessibleContext().setAccessibleName("EXIT");
        j5button1.setLabel("EXIT");

        j5button2.setLabel("RETURN");

        javax.swing.GroupLayout j5Panel1Layout = new javax.swing.GroupLayout(j5Panel1);
        j5Panel1.setLayout(j5Panel1Layout);
        j5Panel1Layout.setHorizontalGroup(
            j5Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j5Panel1Layout.createSequentialGroup()
                .addGroup(j5Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j5Panel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(j5Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(j5textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(j5Panel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(j5button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(j5button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        j5Panel1Layout.setVerticalGroup(
            j5Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j5Panel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(j5textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(j5textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(j5textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(j5textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(j5Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j5button1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(j5button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j5Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j5Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        j5textField1.setText("PLAYER 1 SCORE IS "+ score2);
        j5textField2.setText("PLAYER 2 SCORE IS "+ score3);
        j5textField3.setText("PLAYER 3 SCORE IS "+ score4);
        j5textField4.setText("YOUR SCORE IS "+ score1);
        pack();
    }// </editor-fold>ld>
    

    public void setVal()
    {
	   button1.setLabel(tempstore[0]);
	   button2.setLabel(tempstore[1]);
	   button3.setLabel(tempstore[2]);
	   button4.setLabel(tempstore[3]);
    }
    public int buttonId(Object bt)
    {
    	System.out.println("id is caught");
    	int k=0;
    	if(bt==button1)
    		k=1;
    	else if(bt==button2)
    		k=2;
    	else if(bt==button3)
    		k=3;
    	else if(bt==button4)
    		k=4;
    	return k;
    }
    int k;
    int secondevent=0;
    public void actionPerformed(ActionEvent event)
	{
    	
    	System.out.println("click works");
    	Object source = event.getSource();
    	if(source==j2Button4)
    	{
    	
    		j2Panel1.setVisible(false);
    	//	repaint();
    		initComponents1();
    	}
    	
    	else if(source==j2Button1)
    	{
    		sl = new SingleList();
            temp = sl.head;
    		j2Panel1.setVisible(false);
    		repaint();
    		initComponents3();
    	}
    	else if(source == j3Button1)
    	{
    		j3Panel1.setVisible(false);
    		repaint();
    		initComponents2();
    	}
    	//if(source!=j2Button4) //I changed this.
    	else if(source==j4Button18)
    	{
    		//c = new Card();
    		c.i = 0;
    		//System.out.println("List 1"+c.l1.head.info);
    		generate();
    		this.i = 0;
    		//System.out.println("List 1"+c.l1.head.info);
    		won=false;
    		j4Panel2.setVisible(false);
    		j4Panel1.setVisible(false);
    		//j2Panel1.setVisible(false);
    		
    		initComponents1();
    		//jPanel1.setVisible(true);
    	
    		
    	}
    	else if(source==j4Button17)
    		{
    		//System.exit(0);
    		j4Panel2.setVisible(false);
    		j4Panel1.setVisible(false);
    		initComponents5();
    		}
    	else if(source==j5button1)
    		System.exit(0);
    	else if(source==j5button2)
    	{
    		j5Panel1.setVisible(false);
    		j4Panel2.setVisible(true);
    		j4Panel1.setVisible(true);
    	}
    	else if(source==j2Button3)
    		System.exit(0);
    		
    
    	//else
    	
    		del(source);
    	    game();
    	
		

	}
    
   
    public void generate()
    {
    	c = new Card();
 	    c.generate_random();
 	    c.create_Lists(c.l1);
 	    c.create_Lists(c.l2);
 	    c.create_Lists(c.l3);
 	    c.create_Lists(c.l4);
 	    c.display(c.l1);
 	    DNode temp=c.l1.head;
 	    tempstore[0]=Integer.toString(temp.info);
 	    temp=temp.right;
 	    int index=1;
 	    while(temp!=c.l1.head)
 	    {
 	    	tempstore[index++]=String.valueOf(temp.info);
 	    	temp=temp.right;
 	    }
 	    setVal();
 	    c.display(c.l2);
 	    c.display(c.l3);
 	    c.display(c.l4);
    }
    int id;
    String incoming;
   
    int change=0;
    private void del(Object bt)
    {
		// TODO Auto-generated method stub
    	System.out.println("old value"+ oldval);
    	System.out.println("Entered delete method"+(change++));
    	id=buttonId(bt);
    	System.out.println("came back to del");
    	oldval=tempstore[id-1];
    	tempstore[id-1]="";
    	//t4.start();
    	setVal();
    	
    	//tempstore[id-1]=incoming;
    	
	}
    
    boolean player1;
    boolean player2;
    boolean player3;
    boolean user;
   
	int i=0;
 Color color = getBackground();

 ActionListener first=new ActionListener() 
 {
	
	
		public void actionPerformed(ActionEvent arg0) 
		{
			 player1 = false;
			 player2 = false;
			 player3 = false;
			 user = false;
			if(i==3)
			{
				t3.stop();
			}
			else if(i<3)
			{
				m=array[i];
				//do not increment i here otherwise 2nd button will stay on all the time.
				//repeat++;	
				setmyColor(m);
				if(c.l2.check())
		        {
		            if(i==0)
		            {
		            	System.out.println("player 2 wins");
		            	c.display(c.l2);
			            won=true;
			            player1 = true;
			            System.out.println("GAME END");
			            winner = "Player 1";
			            //Display d=new Display("Player 1", c.l2.head.info, c.l2.head.left.info, c.l2.head.left.left.info, c.l2.head.left.left.left.info);
						//d.show();
			            jPanel1.setVisible(false);
			            initComponents4();
						t1.stop();
						t3.stop();
						t2.stop();
						s2.push(10);
						s1.push(-2);
						s3.push(-2);
						s4.push(-2);
		            }
		            else
		            {
		            	t2.start();
		            }
		      //    break;
		        }
				else if(c.l3.check())
		        {
		            if(i==1)
		            {
						System.out.println("player 3 wins");
			            c.display(c.l3);
			            won=true;
			            player2 = true;
			            s3.push(10);
						s1.push(-2);
						s2.push(-2);
						s4.push(-2);
			            //Display d=new Display("Player 2", c.l3.head.info, c.l3.head.left.info, c.l3.head.left.left.info, c.l3.head.left.left.left.info);
						//d.show();
			            winner = "Player 2";
			            jPanel1.setVisible(false);
			            initComponents4();
						t1.stop();
						t3.stop();
						t2.stop();
		            }
		            else
		            {
		            	t2.start();
		            }
		        //    break;
		        }        
				else if(c.l4.check())
		        {
					if(i==2)
					{
						System.out.println("player 4 wins");
			            c.display(c.l4);
			            won=true;
			            //Display d=new Display("Player 3", c.l4.head.info, c.l4.head.left.info, c.l4.head.left.left.info, c.l4.head.left.left.left.info);
						//d.show();
			            winner = "Player 3";
			            player3=true;
			            s4.push(10);
						s1.push(-2);
						s3.push(-2);
						s2.push(-2);
			            jPanel1.setVisible(false);
			            initComponents4();
						t1.stop();
						t3.stop();
						t2.stop();
			          //  break;
					}
					 else
			            {
			            	t2.start();
			            }
		        }
				else
				{
					t2.start(); //starts delete color event
				}
			} 				
		}
	};
	int repeat=0;
	 ActionListener second=new ActionListener()
	 {
		public void actionPerformed(ActionEvent arg0) 
		{
		 	deleteColor(m);
		 		i++;
		 		//repeat=0;
	     	t2.stop(); //otherwise keeps calling delete color
			if(i<3)
			{
				t3.start(); //calls initial event again
			}
			else if(i==3)
			{
				t3.stop();
				setVal();
				if(c.l1.check())
		        {
		            System.out.println("player 1 win");
		            c.display(c.l1);
		            won=true;
		            user = true;
		            s1.push(10);
					s2.push(-2);
					s3.push(-2);
					s4.push(-2);
		    		//Display d=new Display("User", c.l1.head.info, c.l1.head.left.info, c.l1.head.left.left.info, c.l1.head.left.left.left.info);
		    		//d.show();
		            winner = "User";
		            jPanel1.setVisible(false);
		            initComponents4();
				}//keep setVal only here and nowhere else because we want player's cards to change only after this event
				i=0;
			}
		}
	};
 


 Object m;
 Timer t1=new Timer(300,first);
 Timer t2=new Timer(1000,second);
 Timer t3 = new Timer(30, first); //to call initial event again
 
  String string1="/9067330-smiling-joker-with-cards-and-stars-vector-illustration.jpg";
  String string="/card.jpg";
	public void deleteColor(Object obj)
	{
		//System.out.println("Entered delete method");
		((AbstractButton) obj).setIcon(new javax.swing.ImageIcon(getClass().getResource(string)));
		
	}
 public void setmyColor(Object obj)
 {
 	//System.out.println("Entered set method");
 	((AbstractButton) obj).setIcon(new javax.swing.ImageIcon(getClass().getResource(string1)));
 	t1.stop(); //stop this here because otherwise, t1 keeps getting called until t2 starts.
 }

 public void game()
 {
	 int del;

 	if(i<3) //occurs only for i<3 otherwise resets i=0 for the next time user selects the card
  	{
  		t3.stop(); //stops the event being called too many times
  		System.out.println("entering while i= "+i);
  	    t1.start();//starts set color event
  	}
	
	    //while(true)
	 	if(won!=true)
	    {
	        //System.out.println("enter number to be deleted");
	    	
	    	int k=Integer.parseInt(oldval);
	        c.delete(k,c.l1);
	        c.l2.insert(k);
	       c.display(c.l2);
	        del=c.shift(c.l2.insert, c.l2);
	        c.delete(del, c.l2);
	        c.l3.insert(del);
	        
	       
	        del=c.shift(c.l3.insert, c.l3);
	        c.delete(del, c.l3);
	        c.l4.insert(del);
	        c.display(c.l3);
	      
	        del=c.shift(c.l4.insert, c.l4 );
	        c.delete(del, c.l4);
	        c.l1.insert(del);
	        c.display(c.l4);
	        tempstore[id-1]=String.valueOf(del);
	        incoming=String.valueOf(del);
	        System.out.println("Th deleted value is "+del);
	      
	        c.display(c.l1);
	      
	    c.display(c.l1);
	    c.display(c.l2);
	    c.display(c.l3);
	    c.display(c.l4);
	   
	      }
	 	
	        
	        System.out.println("Th incoming value is "+incoming);
	       
 }
 

	 // public static void main(String args[])
 	//public void displayFrame()
 	public static void main(String args[])
	  {
 		System.out.println("Entering gui display");
 		int test[]=new int[10];
 		System.out.println("Came to display");
		  System.out.println("old value"+oldval);
		  
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                g.setVisible(true);
            }
        });
        test=new int[10];
       
    }
    // Variables declaration - do not modify
   
    Button button1=new Button();
    Button button2=new Button();
    Button button3=new Button();
    Button button4=new Button();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JButton help_button;
    private String newval;
    static String oldval="";
    Object array[] = new Object[3];
    Card c;
   
    //for gui2 variables
    private javax.swing.JButton j2Button1;
    private javax.swing.JButton j2Button3;
    private javax.swing.JButton j2Button4;
    //private javax.swing.JComboBox j2ComboBox1;
    private javax.swing.JDesktopPane j2DesktopPane1;
    private javax.swing.JFrame j2Frame1;
    private javax.swing.JLabel j2Label1;
    private javax.swing.JLabel j2Label2;
    private javax.swing.JLabel j2Label3;
    private javax.swing.JPanel j2Panel1;
    private javax.swing.JScrollPane j2ScrollPane1;
    private javax.swing.JSlider j2Slider1;
    private javax.swing.JTable j2Table1;
    private javax.swing.JComboBox j2ComboBox1;
    final static gui g=new gui();
    
    Node temp;
    //for instruction page
    private javax.swing.JButton j3Button1;
    private javax.swing.JPanel j3Panel1;
    private javax.swing.JScrollPane j3ScrollPane1;
    private javax.swing.JScrollPane j3ScrollPane2;
    private javax.swing.JTextArea j3TextArea1;
    private javax.swing.JTextArea j3TextArea2;
    static boolean won=false;
    // End of variables declaration
    //play again screen
    private javax.swing.JButton j4Button1;
    private javax.swing.JButton j4Button10;
    private javax.swing.JButton j4Button11;
    private javax.swing.JButton j4Button12;
    private javax.swing.JButton j4Button13;
    private javax.swing.JButton j4Button14;
    private javax.swing.JButton j4Button15;
    private javax.swing.JButton j4Button16;
    private javax.swing.JButton j4Button17;
    private javax.swing.JButton j4Button18;
    private javax.swing.JButton j4Button19;
    private javax.swing.JButton j4Button3;
    private javax.swing.JButton j4Button4;
    private javax.swing.JButton j4Button5;
    private javax.swing.JButton j4Button6;
    private javax.swing.JButton j4Button7;
    private javax.swing.JButton j4Button8;
    private javax.swing.JButton j4Button9;
    private javax.swing.JPanel j4Panel1;
    private javax.swing.JPanel j4Panel2;
    private javax.swing.JTextField j4TextField1;
    SingleList sl;
    String winner;
    Stack s1=new Stack();
 	Stack s2=new Stack();
 	Stack s3=new Stack();
 	Stack s4=new Stack();
 	int score1=0,score2=0,score3=0,score4=0;
	//components for score
 	 private javax.swing.JPanel j5Panel1;
     private java.awt.TextField j5textField1;
     private java.awt.TextField j5textField2;
     private java.awt.TextField j5textField3;
     private java.awt.TextField j5textField4;
     private java.awt.Button j5button1;
     private java.awt.Button j5button2;
}
